# Generated by Django 4.1.3 on 2024-01-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="user",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="despesas",
            name="categoria",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="despesas",
            name="user",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ganho",
            name="user",
            field=models.IntegerField(),
        ),
    ]
